/*
 * 2c2p API
 * API implementation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.PaymentRequestPayment;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PaymentRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-18T05:35:09.941Z[GMT]")
public class PaymentRequest {
  @SerializedName("paymentToken")
  private String paymentToken = null;

  @SerializedName("clientID")
  private String clientID = null;

  @SerializedName("locale")
  private String locale = null;

  @SerializedName("responseReturnUrl")
  private String responseReturnUrl = null;

  @SerializedName("payment")
  private PaymentRequestPayment payment = null;

  public PaymentRequest paymentToken(String paymentToken) {
    this.paymentToken = paymentToken;
    return this;
  }

   /**
   * Get paymentToken
   * @return paymentToken
  **/
  @Schema(required = true, description = "")
  public String getPaymentToken() {
    return paymentToken;
  }

  public void setPaymentToken(String paymentToken) {
    this.paymentToken = paymentToken;
  }

  public PaymentRequest clientID(String clientID) {
    this.clientID = clientID;
    return this;
  }

   /**
   * Get clientID
   * @return clientID
  **/
  @Schema(required = true, description = "")
  public String getClientID() {
    return clientID;
  }

  public void setClientID(String clientID) {
    this.clientID = clientID;
  }

  public PaymentRequest locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  @Schema(required = true, description = "")
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public PaymentRequest responseReturnUrl(String responseReturnUrl) {
    this.responseReturnUrl = responseReturnUrl;
    return this;
  }

   /**
   * Get responseReturnUrl
   * @return responseReturnUrl
  **/
  @Schema(required = true, description = "")
  public String getResponseReturnUrl() {
    return responseReturnUrl;
  }

  public void setResponseReturnUrl(String responseReturnUrl) {
    this.responseReturnUrl = responseReturnUrl;
  }

  public PaymentRequest payment(PaymentRequestPayment payment) {
    this.payment = payment;
    return this;
  }

   /**
   * Get payment
   * @return payment
  **/
  @Schema(required = true, description = "")
  public PaymentRequestPayment getPayment() {
    return payment;
  }

  public void setPayment(PaymentRequestPayment payment) {
    this.payment = payment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentRequest paymentRequest = (PaymentRequest) o;
    return Objects.equals(this.paymentToken, paymentRequest.paymentToken) &&
        Objects.equals(this.clientID, paymentRequest.clientID) &&
        Objects.equals(this.locale, paymentRequest.locale) &&
        Objects.equals(this.responseReturnUrl, paymentRequest.responseReturnUrl) &&
        Objects.equals(this.payment, paymentRequest.payment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentToken, clientID, locale, responseReturnUrl, payment);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentRequest {\n");
    
    sb.append("    paymentToken: ").append(toIndentedString(paymentToken)).append("\n");
    sb.append("    clientID: ").append(toIndentedString(clientID)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    responseReturnUrl: ").append(toIndentedString(responseReturnUrl)).append("\n");
    sb.append("    payment: ").append(toIndentedString(payment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
