/*
 * 2c2p API
 * API implementation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentActionApi
 */
@Ignore
public class PaymentActionApiTest {

    private final PaymentActionApi api = new PaymentActionApi();

    /**
     * Get Status on Payment Transaction
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentActionTest() throws ApiException {
        String paymentRequest = null;
        String response = api.paymentAction(paymentRequest);

        // TODO: test validations
    }
}
