/*
 * 2c2p API
 * API implementation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.PaymentTokenRequest;
import io.swagger.client.model.PaymentTokenResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentTokenApi
 */
@Ignore
public class PaymentTokenApiTest {

    private final PaymentTokenApi api = new PaymentTokenApi();

    /**
     * Generate Payment Token
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentTokenTest() throws ApiException {
        PaymentTokenRequest body = null;
        PaymentTokenResponse response = api.paymentToken(body);

        // TODO: test validations
    }
}
