/*
 * 2c2p API
 * API implementation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.PaymentTokenAPIRequest;
import io.swagger.client.model.PaymentTokenAPIResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for PaymentTokenApi
 */
@Ignore
public class PaymentTokenApiTest {

    private final PaymentTokenApi api = new PaymentTokenApi();

    /**
     * Generate Payment Token
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void paymentTokenTest() throws Exception {
        PaymentTokenAPIRequest body = null;
        PaymentTokenAPIResponse response = api.paymentToken(body);

        // TODO: test validations
    }
}
